const OPTIONS = ['None', 'Yes', 'Not sure', 'No'];
const TYPE = {
  POSITIVE: 'positive',
  NEGATIVE: 'negative',
  NEUTRAL: 'neutral',
}

const VALIDATION = SpreadsheetApp.newDataValidation()
  .requireValueInList(OPTIONS, true)
  .build();

const ADJECTIVES = [
  { word: "Ambitious", type: TYPE.NEUTRAL },
  { word: "Amusing", type: TYPE.POSITIVE },
  { word: "Calm", type: TYPE.POSITIVE },
  { word: "Cautious", type: TYPE.NEUTRAL },
  { word: "Charming", type: TYPE.POSITIVE },
  { word: "Chatty", type: TYPE.NEUTRAL },
  { word: "Cocky", type: TYPE.NEGATIVE },
  { word: "Compassionate", type: TYPE.POSITIVE },
  { word: "Competitive", type: TYPE.NEUTRAL },
  { word: "Complex", type: TYPE.NEUTRAL },
  { word: "Confrontational", type: TYPE.NEGATIVE },
  { word: "Conscientious", type: TYPE.POSITIVE },
  { word: "Cowardly", type: TYPE.NEGATIVE },
  { word: "Creative", type: TYPE.POSITIVE },
  { word: "Cynical", type: TYPE.NEGATIVE },
  { word: "Deceitful", type: TYPE.NEGATIVE },
  { word: "Decisive", type: TYPE.NEUTRAL },
  { word: "Defensive", type: TYPE.NEGATIVE },
  { word: "Determined", type: TYPE.POSITIVE },
  { word: "Diligent", type: TYPE.POSITIVE },
  { word: "Disorganized", type: TYPE.NEGATIVE },
  { word: "Disrespectful", type: TYPE.NEGATIVE },
  { word: "Emotional", type: TYPE.NEUTRAL },
  { word: "Empathetic", type: TYPE.POSITIVE },
  { word: "Enigmatic", type: TYPE.NEUTRAL },
  { word: "Extroverted", type: TYPE.NEUTRAL },
  { word: "Forgetful", type: TYPE.NEGATIVE },
  { word: "Funny", type: TYPE.POSITIVE },
  { word: "Generous", type: TYPE.POSITIVE },
  { word: "Gentle", type: TYPE.POSITIVE },
  { word: "Greedy", type: TYPE.NEGATIVE },
  { word: "Grumpy", type: TYPE.NEGATIVE },
  { word: "Gullible", type: TYPE.NEGATIVE },
  { word: "Honest", type: TYPE.POSITIVE },
  { word: "Hostile", type: TYPE.NEGATIVE },
  { word: "Idiosyncratic", type: TYPE.NEUTRAL },
  { word: "Impatient", type: TYPE.NEGATIVE },
  { word: "Introverted", type: TYPE.NEUTRAL },
  { word: "Intuitive", type: TYPE.POSITIVE },
  { word: "Judgemental", type: TYPE.NEGATIVE },
  { word: "Kind", type: TYPE.POSITIVE },
  { word: "Manipulative", type: TYPE.NEGATIVE },
  { word: "Mean", type: TYPE.NEGATIVE },
  { word: "Mischievous", type: TYPE.NEUTRAL },
  { word: "Motivated", type: TYPE.POSITIVE },
  { word: "Optimistic", type: TYPE.POSITIVE },
  { word: "Outspoken", type: TYPE.NEUTRAL },
  { word: "Passionate", type: TYPE.POSITIVE },
  { word: "Patient", type: TYPE.POSITIVE },
  { word: "Pessimistic", type: TYPE.NEGATIVE },
  { word: "Petty", type: TYPE.NEGATIVE },
  { word: "Philosophical", type: TYPE.NEUTRAL },
  { word: "Political", type: TYPE.NEUTRAL },
  { word: "Posessive", type: TYPE.NEGATIVE },
  { word: "Predictable", type: TYPE.NEUTRAL },
  { word: "Rational", type: TYPE.POSITIVE },
  { word: "Rebellious", type: TYPE.NEUTRAL },
  { word: "Reckless", type: TYPE.NEGATIVE },
  { word: "Reliable", type: TYPE.POSITIVE },
  { word: "Reserved", type: TYPE.NEUTRAL },
  { word: "Resourceful", type: TYPE.POSITIVE },
  { word: "Rude", type: TYPE.NEGATIVE },
  { word: "Sarcastic", type: TYPE.NEUTRAL },
  { word: "Selfish", type: TYPE.NEGATIVE },
  { word: "Sensitive", type: TYPE.NEUTRAL },
  { word: "Soft", type: TYPE.NEUTRAL },
  { word: "Solemn", type: TYPE.NEUTRAL },
  { word: "Stingy", type: TYPE.NEGATIVE },
  { word: "Straightforward", type: TYPE.NEUTRAL },
  { word: "Strict", type: TYPE.NEUTRAL },
  { word: "Sympathetic", type: TYPE.POSITIVE },
  { word: "Uncompromising", type: TYPE.NEUTRAL },
  { word: "Vain", type: TYPE.NEGATIVE },
  { word: "Wise", type: TYPE.POSITIVE },
  { word: "Witty", type: TYPE.POSITIVE },
];
